# Generated by Django 5.0.1 on 2024-01-17 16:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_rename_tasks_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='due',
            field=models.DateField(blank=True, default=datetime.date(2024, 1, 17)),
        ),
    ]
