# Generated by Django 5.0.1 on 2024-01-18 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_task_due'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='isCompleted',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
